name: CI & CD Pipeline

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: hello-express
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Build Docker image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-repo/hello-express:${{ github.sha }} \
            .
      - name: Push Docker image
        run: |
          docker push \
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-repo/hello-express:${{ github.sha }}

  deploy-to-app-engine:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: hello-express
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy to App Engine Flex
        run: |
          gcloud app deploy \
            --image-url=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-repo/hello-express:${{ github.sha }} \
            --quiet
