name: CI & CD Pipeline

on:
  push:
    branches:
      - develop
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        id: set-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          fi

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NODE_ENV=${{ env.ENV_NAME == 'prod' && 'production' || 'development' }} \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-repo/hello-express:${{ env.ENV_NAME }}-${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push \
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-repo/hello-express:${{ env.ENV_NAME }}-${{ github.sha }}

  deploy-to-app-engine:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        id: set-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
            echo "APP_YAML=app.prod.yaml" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
            echo "APP_YAML=app.dev.yaml" >> $GITHUB_ENV
          fi

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to App Engine Flex
        run: |
          gcloud app deploy ${{ env.APP_YAML }} \
            --image-url=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-repo/hello-express:${{ env.ENV_NAME }}-${{ github.sha }} \
            --quiet